laravel/octane

- src/Listeners/CreateConfigurationSandbox.php
- src/Listeners/DisconnectFromDatabases.php
- src/Listeners/EnforceRequestScheme.php
- src/Listeners/EnsureRequestServerPortMatchesScheme.php
- src/Listeners/EnsureUploadedFilesAreValid.php
- src/Listeners/FlushArrayCache.php
- src/Listeners/FlushAuthenticationState.php
- src/Listeners/FlushDatabaseRecordModificationState.php
- src/Listeners/FlushLocaleState.php
- src/Listeners/FlushQueuedCookies.php
- src/Listeners/FlushSessionState.php
- src/Listeners/FlushTemporaryContainerInstances.php
- src/Listeners/GiveNewApplicationInstanceToAuthorizationGate.php
- src/Listeners/GiveNewApplicationInstanceToBroadcastManager.php
- src/Listeners/GiveNewApplicationInstanceToHttpKernel.php
- src/Listeners/GiveNewApplicationInstanceToMailManager.php
- src/Listeners/GiveNewApplicationInstanceToNotificationChannelManager.php
- src/Listeners/GiveNewApplicationInstanceToPipelineHub.php
- src/Listeners/GiveNewApplicationInstanceToQueueManager.php
- src/Listeners/GiveNewApplicationInstanceToRouter.php
- src/Listeners/GiveNewApplicationInstanceToValidationFactory.php
- src/Listeners/GiveNewApplicationInstanceToViewFactory.php
- src/Listeners/GiveNewRequestInstanceToApplication.php
- src/Listeners/GiveNewRequestInstanceToPaginator.php
- src/Listeners/PrepareInertiaForNextOperation.php
- src/Listeners/PrepareScoutForNextOperation.php
- src/Listeners/PrepareSocialiteForNextOperation.php
- src/Listeners/ReportException.php
- src/Listeners/StopWorkerIfNecessary.php
Since we use it everywhere else let's also do it on the event listeners.
> Add void return to event listeners

- src/OctaneServiceProvider.php
> Fixed typos

- src/Commands/Concerns/InstallsRoadRunnerDependencies.php
Exceptions are used but not imported
> Add missing imports

- src/Swoole/SwooleClient.php
PHP8 offers a nice new function [str_starts_with](https://www.php.net/manual/de/function.str-starts-with.php)
> [PHP8] Use str_starts_with()

- config/octane.php
> List supported options

- src/Swoole/SwooleExtension.php
> Fix dispatchProcessSignal, check if the process exists before kill

- src/Commands/Concerns/InteractsWithServers.php
Makes it more clear that something went wrong with watching.
> Exit when watcher fails

- src/Concerns/ProvidesConcurrencySupport.php
- src/Exceptions/TaskExceptionResult.php
- src/Swoole/SwooleClient.php
- tests/OctaneStoreTest.php
> fix typo, fix param

- src/Swoole/SwooleClient.php
> fix comment

- src/Swoole/SwooleClient.php
> Allows serve static empty file

- composer.json
This package contains IDE help files for Swoole. You may use it in your IDE to provide accurate autocompletion.
This package is officially released by Swoole.
> Add swoole/ide-helper to require-dev

- src/Worker.php
> Fix typo in handleTask function

- src/Commands/StartRoadRunnerCommand.php
> Handle roadrunner requests reporting duration in microseconds

- README.md
This pull request adds docs about the `octane:stop` command.
> Adds docs about the `octane:stop` command

- src/Concerns/ProvidesDefaultConfigurationOptions.php
- src/Listeners/GiveNewApplicationInstanceToDatabaseSessionHandler.php
Fixes https://github.com/laravel/octane/issues/300
> Give new application instance to database session handler

- src/Swoole/SwooleClient.php
This PR fixes #298 by adding an extra parameter to set the `SameSite` attribute.
> [1.x] Adds SameSite attribute for cookies

- config/octane.php
Two listeners were missing in the default config. This adds them.
> Add missing default listeners

- src/Commands/StartRoadRunnerCommand.php
> fix config key for roadrunner http.middlware

- src/Concerns/ProvidesDefaultConfigurationOptions.php
- src/Listeners/FlushLogContext.php
> [1.x] Flush any log context after each operation

- bin/createSwooleServer.php
PHP Warning:  Undefined array key "swoole" in /var/www/vendor/laravel/octane/bin/createSwooleServer.php on line 10
> Undefined array key "swoole"

- src/Listeners/GiveNewApplicationInstanceToAuthorizationGate.php
- src/Listeners/GiveNewApplicationInstanceToDatabaseSessionHandler.php
- src/Listeners/GiveNewApplicationInstanceToRouter.php
- src/Listeners/GiveNewApplicationInstanceToViewFactory.php
follow up https://github.com/laravel/octane/pull/355
> [1.x] Resolve components when needed (2)

- src/Swoole/SwooleTaskDispatcher.php
Fixes https://github.com/laravel/octane/issues/395
> [1.x] Fix issue where timed out tasks were not taken into account

- bin/roadrunner-worker
> Remove unuse `use` statement

- README.md
This pull request adds links to Swoole / Open Swoole documentation.
Replaces #439
> [1.x] Adds links to Swoole / Open Swoole documentation

- src/Commands/StartRoadRunnerCommand.php
There was the PR to master which is fixes the issue #450 but it was not merged to the last version. The same fix is here
> Log level fix

- tests/FilesystemManagerStateTest.php
Fixes failing build introduced in #458.
> Fix FilesystemManagerStateTest

- src/Commands/Concerns/InteractsWithIO.php
- tests/CommandTest.php
This pull request fixes the conversion of memory value, from bytes to megabytes.
> [1.x] Fix byte conversion

- src/Concerns/ProvidesDefaultConfigurationOptions.php
- src/Listeners/RefreshQueryDurationHandling.php
Dependent on: https://github.com/laravel/framework/pull/42744
> Refresh query duration handling

- src/Swoole/SwooleClient.php
> Added status codes (RFC6585 & RFC7725)

- src/Commands/StartRoadRunnerCommand.php
> Revert "[1.x] Made Roadrunner log level configurable"

- src/Swoole/SwooleExtension.php
- tests/SwooleExtensionTest.php
This pull request adds support for Open Swoole `v22.x`, while still support older versions of Open Swoole and regular Swoole.
> [1.x] Adds support for Open Swoole `v22.x`

- .github/workflows/tests.yml
- composer.json
This pull request adds Laravel 10 support to Octane.
> [1.x] Adds Laravel 10 support

- composer.json
This pull request makes Collision compatible with Collision `v7.x`.
> [1.x] Adds support for Collision `v7.x`

- .gitattributes
- .github/workflows/static-analysis.yml
- composer.json
- phpstan.neon.dist
- src/Swoole/Handlers/OnWorkerStart.php
This pull request adds type checking to this repository.
> [1.x] Adds type checking

- src/Commands/StartCommand.php
Hi! 
I need debug log level in staging (and also for part of production servers).
> --log-level option in octane:start command

- .github/workflows/tests.yml
- src/Commands/StartRoadRunnerCommand.php
- src/Commands/StartSwooleCommand.php
- src/RoadRunner/Concerns/FindsRoadRunnerBinary.php
- src/SymfonyProcessFactory.php
- src/Worker.php
> Revert "PHP 8.3"

- src/Commands/Concerns/InteractsWithIO.php
- src/Commands/StartFrankenPhpCommand.php
This pull request fixes `NGINX` proxy usages.
> [2.x] Fixes `NGINX` proxy usages

- src/Commands/Concerns/InstallsFrankenPhpDependencies.php
This pull request validates if there is a version before using it.
> [2.x] Validates if there is a version before using it

- src/Commands/stubs/Caddyfile
Fixes https://github.com/laravel/octane/issues/781
See https://github.com/laravel/octane/issues/781#issuecomment-1866504761 for the explanation
> Fix Caddyfile when env var values contain spaces

- src/Commands/Concerns/InstallsFrankenPhpDependencies.php
frankenphp just released a build for arm64 for linux:
https://github.com/dunglas/frankenphp/releases/tag/v1.0.2
> [2.x] Added `aarch64` binary for frankenphp 

- composer.json
> Revert "[2.x] Require pcntl extension"
