src/RoadRunner/ServerProcessInspector.php
As per documentation the RR command is `reset {service}`, i.e. `reset http`. Command without args `reset` will reset all the plugins.
Current code uses older (v1) reset commands dedicated to HTTP only.
Reference: https://roadrunner.dev/docs/beep-beep-cli
=> [WIP] Fix the RR reset command

src/Facades/Octane.php
Adds the methods from the `\Laravel\Octane\Octane` class and concerns to the facade doc block for better IDE support, similar to other facades of the framework.
Not sure if all of the documented methods are already considered stable enough to be documented here, I primarily added it for the `concurrently($tasks)` method.
=> Add methods to facade doc block

README.md
This probably isn't needed anymore now that we've updated all of them.
=> Remove packages list

src/Swoole/SwooleCoroutineDispatcher.php
Because short names can be turned off with a configuration item
```ini
swoole.use_shortname=off
```
=> Use Coroutine's full name instead of the short name

src/Commands/Concerns/InstallsRoadRunnerDependencies.php, src/Commands/StartRoadRunnerCommand.php
This is similar to the Swoole command, makes sure the current PHP version is used (eg. when using multiple PHP versions)
=> Use PhpExecutableFinder for Octane server command

src/Commands/ReloadCommand.php, src/Commands/StartCommand.php, src/Commands/StopCommand.php
For example, if I type `php artisan octane:start --server=swole`, the `roadrunner` server is started.
=> Handle invalid server option in `octane:start/reload/stop`

src/Commands/Concerns/InteractsWithServers.php
A minor change from "Use" to "Press" seems more appropriate.
=> Minor word change

src/Exceptions/TaskExceptionResult.php, src/Stream.php
In PHP 8 we can finally use the `::class` notation on objects to get their FQN.
=> Use new class notation

src/Commands/Concerns/InteractsWithServers.php, src/OctaneServiceProvider.php, src/SequentialTaskDispatcher.php, src/Swoole/SwooleHttpTaskDispatcher.php, tests/SequentialTaskDispatcherTest.php
In PHP 8 it's no longer necessary to add these.
=> Remove variables in catches

src/Swoole/SwooleExtension.php
`swoole_set_process_name` is actually also a call to `cli_set_process_title`
So it's better to use `cli_set_process_title` directly
=> Use cli_set_process_title instead of swoole_set_process_name

.gitignore, src/Swoole/SwooleClient.php
Hello guys, I did a test, substr() has no memory overhead and is more efficient than str_split().
```php
$bigStr = str_repeat('abcdefghijklmnopqrstuvwxyz0123456789', 1000000);
$memStart = memory_get_usage(true);
$timeStart = microtime(true);
// ----- substr()
$len = strlen($bigStr);
$chunkLimit = 4096;
for ($offset = 0; $offset < $len; $offset += $chunkLimit) {
$chunk = substr($bigStr, $offset, $chunkLimit);
}
// ----- str_split()
//$chunkLimit = 4096;
//foreach (str_split($bigStr, $chunkLimit) as $chunk) {
//}
$costMem = memory_get_usage(true) - $memStart;
$costTime = microtime(true) - $timeStart;
echo "Memory: {$costMem} Time: {$costTime}\n";
```
```
// substr()
Memory: 0 Time: 0.0036599636077881
// str_split()
Memory: 2097152 Time: 0.043421983718872
``` …
=> Optimized the memory usage when writing chunks

bin/bootstrap.php, src/Commands/Concerns/InteractsWithIO.php, src/Exceptions/DdException.php, src/Exceptions/TaskExceptionResult.php, src/Listeners/ReportException.php, src/OctaneServiceProvider.php, tests/Listeners/ReportExceptionTest.php, tests/SequentialTaskDispatcherTest.php, tests/SwooleHttpTaskDispatcherTest.php, tests/SwooleTaskDispatcherTest.php
This pull request makes `dd` compatible with Octane.
=> Makes `dd` compatible with Octane

README.md, bin/file-watcher.js, config/octane.php, src/Commands/Concerns/InteractsWithServers.php
This pull request makes watch paths configurable. If we release this feature under the `0.1.x` series, people will need update their `config/octane` file to be able to use the watch feature.
**Note for @taylorotwell :** On the `config/octane.php` file, we need to adjust the configuration description.
Fixes https://github.com/laravel/octane/issues/118.
=> Makes watch paths configurable

src/Commands/StartRoadRunnerCommand.php, src/Commands/stubs/rr.yaml
With the new basic Roadrunner config file .rr.yaml, it allows us to run [rr commands](https://roadrunner.dev/docs/beep-beep-cli) in the terminal and Octane Healthcheck endpoint. (This PR is for the issue #104)
Ex: To view the status of all active workers.
`rr workers`
Ex: To reset without restart Octane 
`rr reset`
Ex: Healthcheck - Includes a health check endpoint that returns the health of the workers.
http://localhost:2114/health?plugin=http
=> Added basic roadrunner configs for healthcheck and rr commands

README.md, src/Contracts/Client.php, src/OctaneResponse.php, src/RoadRunner/RoadRunnerClient.php, src/Swoole/SwooleClient.php, src/Testing/Fakes/FakeClient.php, src/Worker.php, tests/RoadRunnerClientTest.php, tests/SwooleClientTest.php
This PR collects the output buffer and prepends it to the response.
It also handles StreamedResponses as reported in https://github.com/laravel/octane/issues/109. However, It'll collect the response and send it at the end of the request, it won't **stream** it.
=> Collect output buffer so echo, var_dump(), and dump() work

tests/RoadRunnerClientTest.php, tests/SwooleClientTest.php
Adds tests from https://github.com/laravel/octane/pull/151 to check the StreamedResponses are working
=> Test streamed response

src/Exceptions/TaskExceptionResult.php, src/Swoole/Actions/EnsureRequestsDontExceedMaxExecutionTime.php, src/Swoole/Handlers/OnWorkerStart.php, src/Swoole/InvokeTickCallable.php, src/Swoole/SwooleHttpTaskDispatcher.php
Currently, two different multi-line constructor formats are used. This PR changes the format to a common one (which is used more frequently throughout the code base already).
Not very common:
https://github.com/laravel/octane/blob/c306e59ddcd2c6ffbd5ff5241ce58cdc9b5fa2b5/src/Swoole/Actions/EnsureRequestsDontExceedMaxExecutionTime.php#L9-L13
Common:
https://github.com/laravel/octane/blob/c306e59ddcd2c6ffbd5ff5241ce58cdc9b5fa2b5/src/Swoole/ServerProcessInspector.php#L9-L13
=> Reformat multi-line constructors

src/RoadRunner/ServerProcessInspector.php
If the process exits, throw an error so it's more clear.
In my case it says this, but not sure if that's just me. At least for now show that it fails.
```
INFO  Reloading workers...
Symfony\Component\Process\Exception\ProcessFailedException 
The command "'./rr' 'reset'" failed.
Exit Code: 1(General error)
Working directory: /home/barry/www/octane
Output:
================
Error Output:
================
rpc service disabled
```
=> Reload must run, otherwise throw error

src/Swoole/SwooleClient.php
It's not in the swoole docs but by testing, if we use `$swooleResponse->write($content);` once we cannot use `$swooleResponse->end($content);`. The content passed to `end()` will be ignored.
This PR does all writing with `write()`.
=> Use swooleResponse->write() to write all output.

src/RoadRunner/ServerProcessInspector.php, tests/RoadRunnerServerProcessInspectorTest.php
Sorry for the 2nd attempt after https://github.com/laravel/octane/pull/178, but `mustRun()` and the previous `run()` seem to not work in my server. Not sure why but it seems like this issue, where it exists to fast; https://github.com/symfony/symfony/issues/7237
In my case it just kept blocking. If I debugged the output, I only got a small part (`OUT > Res… `) and then just kept waiting.
This still throws an exception when something is passed on the error output.
(In my case `.rr.yaml` wasn't updated yet to start the rpc service, hence the failure)
=> Use start instead of run

src/Worker.php
This PR fixes memory leaks in Octane as reported in https://github.com/laravel/octane/issues/171
---
```
$sandbox->flush();
```
This will flush the entire sandbox container. This will clear any references to request-content singletons which allows PHP's garbage collector from clearing the memory when `unset($sandbox)` is called.
---
```
$this->app->make('view.engine.resolver')->forget('blade');
$this->app->make('view.engine.resolver')->forget('php');
```
These lines deal with a memory leak in facade/ignition as explained in https://github.com/laravel/framework/pull/36955.
=> Fix memory leaks

bin/swoole-server, src/Swoole/Handlers/OnWorkerStart.php
Set the process name when worker starts. In this way, we can clearly know how many worker processes there are and how many task worker processes there are.
=> Set the process name when worker starts

src/Swoole/Actions/ConvertSwooleRequestToIlluminateRequest.php, tests/SwooleClientTest.php
Fixes Request URI from Swoole, fixes https://github.com/laravel/octane/issues/188
See also https://github.com/swooletw/laravel-swoole/issues/311 for a related issue. It seems Swoole doesn't correctly set the REQUEST_URI, but I can't really understand the discussion in Chinese..
=> Add querystring to request uri

src/Swoole/SwooleClient.php
Without this, the following exception is thrown.
=> Handle empty responses

src/RoadRunner/ServerProcessInspector.php, tests/RoadRunnerServerProcessInspectorTest.php
This pull request adjusts the RR ReloadCommand so it only considers the process "started" when some output is printed.
=> Adjust reload command

bin/bootstrap.php, src/Commands/StopCommand.php, src/Swoole/ServerProcessInspector.php, src/Swoole/SignalDispatcher.php
* In the old terminate method, when `$this->canCommunicateWith($processId)` is true, it returns true directly, but this actually indicates that the process still exists.
* The current `octane:stop` command does not determine whether the process exits successfully, and the user does not know whether the process finally exits successfully.
=> Report error when server fails to stop, waits server to stop.

src/Commands/Concerns/InteractsWithServers.php, src/Commands/StartCommand.php, src/Commands/StartRoadRunnerCommand.php, src/Commands/StartSwooleCommand.php
This pull request fixes the fact that "octane:stop" was not being called when signals were sent from the supervisor.
=> Fixes "octane:stop" not being called when TERM signal is sent from supervisor

src/Commands/StartRoadRunnerCommand.php, src/Commands/StartSwooleCommand.php
Method call is provided 2 parameters, but the method signature uses 1 parameters
=> Fix option param error

src/Commands/stubs/rr.yaml
This pull request reverts:  https://github.com/laravel/octane/pull/149.
If multiple roadrunner servers are running in the same server, the `octane:start` command will fail because of:
```
ERROR  2021-04-16T12:11:38.712+0100	ERROR	container/poller.go:16	vertex got an error	{"vertex id": "status.Plugin", "error": "listen tcp4 127.0.0.1:2114: bind: address already in use"}
```
=> Fixes starting multiple roadrunner servers

src/Commands/StatusCommand.php, src/OctaneServiceProvider.php
This pull request adds the command `octane:status` - just like `horizon:status`. The goal is allow the user to check the current status of an octane server without having to use the `stop` or `start` commands.
=> Adds `octane:status` command

README.md, src/Commands/Concerns/InstallsRoadRunnerDependencies.php, src/Commands/InstallCommand.php, src/Commands/StartRoadRunnerCommand.php, src/Commands/StartSwooleCommand.php, src/Swoole/SwooleExtension.php
This pull request improves the install command by:
1. Asking the user `Which application server you would like to use?`.
2. Installing the needed dependencies for the chosen server.
3. Adding the needed environment variables, such as `OCTANE_SERVER`.
4. And, by not allowing to run a server if the server dependencies are not installed correctly:
=> Improves `octane:install` command

README.md
This pull request adds docs about the `octane:status` command.
=> Adds docs about the `octane:status` command

src/Commands/StartCommand.php, src/Commands/StartRoadRunnerCommand.php, src/RoadRunner/ServerProcessInspector.php, tests/RoadRunnerServerProcessInspectorTest.php
This pull request makes RoadRunner start command to set a different RPC port foreach RoadRunner server. Note that, just like `host` or `port` artisan options, the `rpc-port` can not be set using the `.rr.yaml` file.
=> Fixes RoadRunner `octane:reload` by setting a different RPC port per server

README.md
I guess this is no longer the case.
=> Removes "We are still in the process of ensuring Octane compatibility with Laravel packages"

src/Concerns/ProvidesDefaultConfigurationOptions.php, src/Listeners/GiveNewApplicationInstanceToDatabaseManager.php
Depends on https://github.com/laravel/framework/pull/37068
=> Give new app instance to database manager

src/Commands/StartSwooleCommand.php
`SWOOLE_LOG_TRACE` => 1
`SWOOLE_LOG_INFO` => 2
`SWOOLE_LOG_ERROR` => 5
When using `1` you need to add the `-enable-trace-log` option to compile Swoole, Default is `2`.
=> Use constants instead of hard coding

src/Commands/Concerns/InstallsRoadRunnerDependencies.php, src/Commands/StartRoadRunnerCommand.php
This pull request ensures the RR binary people download always meet Octane's requirements.
So when people run `octane:start`, and a binary already exists, we are going to check if the binary contains a version equal or superior to `$requiredVersion = '2.0.4';`. If the version is below these requirements, we are going to download the most recent version:
Note that, by default the answer is `yes`. So Deamons/Supervisors will eventually update the `rr` binary if needed when they run `octane:start`.
If something fails in the process ( no internet, wtv ) we keep using the outdated version:
@taylorotwell Note that we don't always update the binary ( only when is really needed ). I've done this so if RoadRunner releases a version with a "bug", only new users using octane will be impacted.
=> Ensure RoadRunner binary is up-to-date

src/Commands/StartRoadRunnerCommand.php
Hi,
we are getting errors in `calculateElapsedTime` method since it is not removing string before multiply. 
```
ErrorException 
A non-numeric value encountered
at vendor/laravel/octane/src/Commands/StartRoadRunnerCommand.php:209
205▕         if (Str::endsWith($elapsed, 'µs')) {
206▕             return $elapsed * 0.001;
207▕         }
208▕ 
➜ 209▕         return $elapsed * 1000;
210▕     }
211▕ 
212▕     /**
213▕      * Stop the server.
```
This PR also fixes return type and force input string value to be float.
=> Remove µs string before multiply, fix return type

src/Swoole/SwooleExtension.php
If the Swoole extension is not loaded, but there is code in other composer packages such as:
```php
var_dump(extension_loaded('swoole'));
if (!function_exists('swoole_cpu_num')) {
function swoole_cpu_num()
{
return 1;
}
}
var_dump(function_exists('swoole_cpu_num'));
//bool(false)
//bool(true)
```
This creates an error.
=> Use extension_loaded instead of function_exists

CHANGELOG.md, src/Commands/Concerns/InteractsWithEnvironmentVariables.php, src/Commands/StartRoadRunnerCommand.php, src/Commands/StartSwooleCommand.php
This pull request fixes global environment variables not being taken in by workers. In addition, it fixes the fact that the `environment` value was not being taken by workers too.
Fixes #244.
=> Fixes global environment variables not being taken in by workers

CHANGELOG.md, src/Commands/Concerns/InstallsRoadRunnerDependencies.php, src/Commands/StartRoadRunnerCommand.php
This pull request removes a non needed "dotenv" option in RoadRunner.
=> Removes non needed "dotenv" option in roadrunner

src/Commands/StartSwooleCommand.php
Fix #260
Swoole v4.6.7 is released, The limitation of `output_buffer_size` is removed and default value `output_buffer_size` is changed from 2MB to UINT_MAX.
=> Remove buffer_output_size from Swoole's default options

src/Commands/Concerns/InstallsRoadRunnerDependencies.php, src/RoadRunner/Concerns/FindsRoadRunnerBinary.php, src/RoadRunner/ServerProcessInspector.php, tests/RoadRunnerServerProcessInspectorTest.php
This PR fixes issue #287 by introducing a new trait to find the RoadRunner binary if present, otherwise return null.
=> Reload RoadRunner using the global executable if it's present

src/Swoole/SwooleClient.php, tests/SwooleClientTest.php
This PR fixes #291 by passing an extra parameter `$reason` for non-standard HTTP codes.
=> Fixes issue related to changing non-standard HTTP status codes to 200 OK

src/Commands/Concerns/InteractsWithIO.php, tests/CommandTest.php
Since the Laravel documentation does not provide how to check for memory leaks, many developers will opt in to use the Laravel debug bar, but i found out that the debug bar it has a memory leak itself,  so displaying the memory usage besides the duration of each request will help to easy spot memory leaks without external tools.
=> Display memory usage

src/Commands/Concerns/InteractsWithIO.php, src/Stream.php, tests/CommandTest.php
This pull request improves the https://github.com/laravel/octane/pull/297 pull request by displaying the memory usage from workers instead of the memory of the "output" process.
In addition, it **only displays the memory** while using Swoole. As the memory output seems not be available when using Roadrunner.
=> Displays memory usage from workers and only on swoole

src/Commands/StartSwooleCommand.php
The swoole server acknowledges a log entry as something else (a request I guess) and routes it to handleStream when the log entry is a valid JSON.
I don't know if there is any other better way to solve it, but when receiving a json before routing it to handleStream, adding a check for the required type key as well at least solves the issue for the format in Monolog\Formatter\JsonFormatter
It would still conflict with other logs that:
1. Are valid json
2. Contains the key type
=> [1.x] Fix Swoole breaks when log is a valid JSON

src/Commands/Concerns/InteractsWithIO.php, src/Commands/StartRoadRunnerCommand.php, src/Commands/StartSwooleCommand.php
This pull request addresses https://github.com/laravel/octane/issues/320, https://github.com/laravel/octane/pull/325, by proxy applications logs (using `stderr` driver) to `stderr`.
=> Prints server logs to "stderr"

config/octane.php, src/Commands/StartRoadRunnerCommand.php
Roadrunner `http.middlware` config is currently hardcoded to "static" in  `src/Commands/StartRoadRunnerCommand.php` file, and thus cannot be changed via .rr.yaml file
This pull request set this as an option in `config/octane` file in order to customize it following the official conf : https://roadrunner.dev/docs/intro-config
The main purpose is to allow to enable gzip as this is one the supported middleware option.
Ex : `    'http_middleware' => 'static,gzip'`
=> Set roadrunner http.middlware as an option

src/Commands/StartCommand.php, src/Commands/StartRoadRunnerCommand.php
Submitted with intentions for a first review and consideration.
Reasons for this pull request:
1. As mentioned in #332: to be able use different ``.rr.yaml`` based on different environments
2. We use ``deployer``. As this is symbolic link deployment, the ``base_path()`` picks up the path from the ``releases/<id>`` reference instead of the symb link. It'd be nice if we could provide a path via cli.
The first option is more encouraging, as this config file is most likely to be on the server in a different location.
=> Addresses #332: pass config-file path for roadrunner

bin/createSwooleServer.php, config/octane.php
I find no PR for this issue #155, so i create this.
Propose to expose SWOOLE_SSL flag and configurable in `config/octane.php`. 
User can just toggle the flag then `sail down` and `up` to turning HTTPS on/off without docker re-build.
Since the latest Sail using `php8.0-swoole`, [Sail PR](https://github.com/laravel/sail/pull/177), 
User should be able to turn on HTTPS support easily by just editing `Dockerfile` & `docker-compose.yml`
Adding the flag `octane.swoole.enable-openssl` & `octane.swoole.options` in the config, so it will not affect default Swoole HTTP setup but easy for user to configure swoole.
=> expose the flag to turn on SWOOLE_SSL

bin/createSwooleServer.php, src/Commands/StartSwooleCommand.php
This pull request addresses an issue where `SWOOLE_SSL` constant was being used even if the `openssl` was not configured on swoole causing the following error: `Undefined constant SWOOLE_SSL`.
With this pull request, the `SWOOLE_SSL` is only used if the user have enabled `openssl` on swoole and configured octane to use ssl.
=> [1.x] Avoids usage of `SWOOLE_SSL` when `openssl` is not configured on swoole

src/Listeners/FlushAuthenticationState.php, src/Listeners/FlushQueuedCookies.php, src/Listeners/FlushSessionState.php
In my app i dont have any Auth, Cookie, Session system (telegram app) so:
=> [1.x] Resolve components when needed

.github/workflows/tests.yml, src/Cache/OctaneStore.php, tests/OctaneStoreTest.php, tests/TestCase.php
Swoole has removed `Swoole\Table\Row` since v4.7.0 (https://github.com/swoole/swoole-src/pull/4297), so you can't read or write `Table` as an array anymore.
This PR is compatible with lower versions of Swoole. 
Of course, Swoole doesn't recommend using arrays for reading and writing, but rather using `API`.
=> [1.x] Fix the bug of Swoole\Table using array access

src/Swoole/SwooleTaskDispatcher.php, tests/SwooleTaskDispatcherTest.php
Swoole's `taskWaitMulti` method expects a timeout value in seconds, however, Octane is providing a timeout value in milliseconds: https://www.swoole.co.uk/docs/modules/swoole-server-taskWaitMulti
This PR divides the given millisecond value by 1000 when passing into `taskWaitMulti`.
=> Fix timeout value passed to taskWaitMulti

src/Swoole/Handlers/OnWorkerStart.php
Fix #384
If PHP has APCu/OPcache enabled, reloads will be affected when reloading, so you need to clear the cache
=> Add clear the cache of APCu and Opcache

src/Concerns/ProvidesDefaultConfigurationOptions.php, src/Listeners/FlushDatabaseQueryLog.php
As mentioned in #392 , when database query logging is enabled, the logs are not cleared after a request is handled. This PR fixes that issue by introducing a new listener([FlushDatabaseQueryLog](https://github.com/nazmulpcc/octane/blob/a6f462573f975452cf486e8473d8b4adc2202858/src/Listeners/FlushDatabaseQueryLog.php) ) that calls `flushQueryLog` on each db connections.
=> add FlushDatabaseQueryLog for cleaning up database query log

src/Commands/Concerns/InteractsWithIO.php
This PR fixes an edge case where the stream type is undefined when using the `dump` function, with an empty array.
For example
This works without problems
```php
public function foo()
{
// ...do something
dump(['foo'=>'bar']);
}
```
But this crashed the swoole server
```php
public function foo()
{
// ...do something
dump([]);
}
```
With the followring error:
```
ErrorException 
Undefined array key "type"
at vendor/laravel/octane/src/Commands/Concerns/InteractsWithIO.php:231
227▕     public function handleStream($stream, $verbosity = null)
228▕     {
229▕       
230▕ 
➜ 231▕         match ($stream['type']) {
232▕             'request' => $this->requestInfo($stream, $verbosity),
233▕             'throwable' => $this->throwableInfo($stream, $verbosity),
234▕             'shutdown' => …
```
=> Fix undefined array key "type" on empty array dump

composer.json, src/Concerns/ProvidesDefaultConfigurationOptions.php, src/Listeners/FlushTranslatorCache.php, tests/Listeners/FlushTranslatorCacheTest.php
This pull request fixes a memory leak on the `Translator` implementation where the `parsed` translation keys cache was not being "flush" on each request.
Fixes https://github.com/laravel/octane/issues/415.
=> [1.x] Fixes memory leak on Translator implementation

src/Exceptions/TaskExceptionResult.php, src/Stream.php
This pull request fixes an issue introduced when migrating to https://github.com/laravel/serializable-closure, where errors reported from concurrently ( at the root level of the task ) were causing the server to shutdown.
Fixes #418
=> [1.x] Fixes server shutting down on concurrently when exceptions are reported at root level of the task

src/Commands/InstallCommand.php
This pull request updates `octane:install` command when Swoole extension is missing. 
With this pull request, if the extension is missing, we display a warning saying that the extension is missing, yet the installation proceeds by adding the necessary environment variable the `.env` file. This is necessary as people usually, install Octane in their OS, but run Octane in their Sail environment.
g
=> [1.x] Updates `octane:install` command when Swoole extension is missing

.github/workflows/tests.yml, tests/SwooleClientTest.php
This pull request fixes the Octane's test suite by skipping tests - regarding Open Swoole workflow - that require to mock Open Swoole's Response class. The issue relies on mockery or phpunit not being able to mock that Open Swoole's Response class because of some weird `eval` error that tries to declare a function like so: `public function header(): false;`.
In addition, this pull request also removes the "continue-on-error" that we have added for Swoole with PHP 8.1.
=> [1.x] Skip tests on Open Swoole that require mocking Open Swoole's Response class

src/Commands/Concerns/InteractsWithServers.php, src/Commands/StartRoadRunnerCommand.php, src/Commands/StartSwooleCommand.php
This pull request fixes an edge case where the temporary file created by Octane's Symfony process for the process's output, may take a considerable disk space, if the process is running for too long. In addition, we don't really need that full output, as we already use it the `getIncrementalOutput` for getting incrementally the output.
So, the solution in this pull request is simple, we just clear the output - the temporary file - every time we grab information from the output.
Closes https://github.com/laravel/octane/issues/426
=> [1.x] Fixes Octane's process output not being flushed

src/Commands/StartCommand.php, src/Commands/StartRoadRunnerCommand.php, src/Commands/StartSwooleCommand.php
This pull request addresses #341 for the swoole part. And this introduce the new option - `raw-server-output` to make sure we only use raw format for method `writeServerOutput` in `StartSwooleCommand`
=> [1.x] Add new option that strict raw server output for swoole.

bin/roadrunner-worker
When using Roadrunner, users may use `http.pool.supervisor.ttl` configuration option to restart workers every X seconds.
This pull request fixes an issue when workers are being restarted without ever been booted - this happens a worker receives 0 requests.
Fixes #443
=> [1.x] Fixes `call terminate() on null` when worker is not booted

src/Commands/Concerns/InstallsRoadRunnerDependencies.php, src/Commands/Concerns/InteractsWithIO.php, src/Commands/StartRoadRunnerCommand.php
This pull request addresses https://github.com/laravel/octane/issues/448, by fixing the non-displayable HTTP request logs, and fixing the display of some messages such as "worked allocated" or "Server started",  since RoadRunner RoadRunner `v2.6.x`:
The underlying issue relies on the fact that RoadRunner now logs HTTP requests a little bit differently, and this pull request accommodates those changes.
Because this pull request makes Octane require RoadRunner `^2.6.0`, I've also changed the `requiredVersion` constant. No worries, the current code still compatible with older versions, but HTTP logs won't be printed on development.
=> [1.x] Adds support for RoadRunner `v2.6.x`

src/Commands/StartRoadRunnerCommand.php
There was wrong log level used.
Documentation reference: https://github.com/spiral/roadrunner-binary/blob/master/.rr.yaml#L84
Release Notes: https://github.com/spiral/roadrunner-binary/releases/tag/v2.2.0
Issue #450
=> The Issue #450 fix

.github/workflows/tests.yml, src/Tables/SwooleTable.php
Fix #446
Although Swoole has been fixed, a compatibility needs to be done.
Also type declaration will be added in the [v5](https://github.com/swoole/swoole-src/commit/6da32cf3d64f743b87bd2d4c8025876bfa10c9a9) version.
=> Fix type declaration error of Swoole table

composer.json, src/Concerns/ProvidesDefaultConfigurationOptions.php, src/Listeners/GiveNewApplicationInstanceToFilesystemManager.php, tests/FilesystemManagerStateTest.php
`FilesystemManager` and its custom/extended drivers rely on the `$filesystemManager->app` instance to provide the app config. If the config changes at runtime (e.g. multi-tenancy environment or via a package service provider) the `FilesystemManager` keeps using the old application instance and the wrong config values.
This PR uses https://github.com/laravel/framework/pull/40058 to fix this issue. A test is included and the `laravel/framework` version is bumped to make sure the `FilesystemManager::setApplication()` method from the aforementioned PR is always available.
=> Give the current App instance to FilesystemManager 

src/Concerns/ProvidesDefaultConfigurationOptions.php, src/Listeners/FlushMonologState.php, tests/Listeners/FlushMonologStateTest.php
This pull request ensures the monolog state - handlers and processors - are reset between requests.
An example is on the usage of `FingersCrossedHandler`. Previously, when using the `FingersCrossedHandler`, the following requests printed two logs:
```php
Route::get('/info', fn () => info('info'));
Route::get('/critical', fn () => logger()->critical('critical'));
// 2 requests...
GET /info
GET /critical
// laravel.log (Assuming an `'action_level' => 'critical'`)
line 1: info
line 2: critical
```
Now, because the `FingersCrossedHandler` is flushed between requests, the output is:
```php
// 2 requests...
GET /info
GET /critical
// laravel.log (Assuming an `'action_level' => 'critical'`)
line 1: critical
```
=> [1.x] Flush monolog state between requests

bin/WorkerState.php, src/Swoole/Handlers/OnWorkerStart.php
Users will be able to access $server status and methods like [app(WorkerState::class)->server->stats()](https://openswoole.com/docs/modules/swoole-server-stats) within the application.
=> [1.x] Allow users to access $server with in Controller

composer.json, src/Concerns/ProvidesDefaultConfigurationOptions.php, src/Listeners/FlushStrCache.php, tests/Listeners/FlushStrCacheTest.php
This pull request fixes https://github.com/laravel/octane/issues/466, by flushing the `Str` between requests.
=> [1.x] Flushes `Str` cache between requests

.github/workflows/tests.yml, src/Swoole/SwooleClient.php
This PR enables deprecation throwing and fixes an issue with passing `null` for the `$domain` parameter for a cookie which isn't allowed anymore.
Fixes https://github.com/laravel/telescope/issues/1189
=> [1.x] Fix passing null to cookie for domain

composer.json, src/Commands/Concerns/InstallsRoadRunnerDependencies.php, src/Commands/Concerns/InteractsWithIO.php, src/Commands/StartRoadRunnerCommand.php
Since RoadRunner [v2.8.0](https://github.com/roadrunner-server/roadrunner/releases/tag/v2.8.0), it's necessary to add the `version: 2.7` instruction on the `.rr.yaml` file.
This pull request makes this change easy to Octane developers, by setting `version: 2.7` automatically, and forcing them to use the latest version of the binary.
Waiting for: https://github.com/roadrunner-server/roadrunner/issues/1021.
Fixes: https://github.com/laravel/octane/issues/479.
=> [1.x] Fixes missing `version` option

bin/file-watcher.js, src/Commands/Concerns/InteractsWithServers.php, src/Commands/StartCommand.php, src/Commands/StartRoadRunnerCommand.php, src/Commands/StartSwooleCommand.php
This pull request fixes `--watch` files over a network: typically environments such as Laravel Sail, or Windows environments. 
Looking at the documentation, this may increase the CPU usage: https://github.com/paulmillr/chokidar. So, lets stay vigilant to see if someone complains about this change. 
Fixes #487
=> [1.x] Fixes `--watch` files over a network

src/Listeners/FlushTemporaryContainerInstances.php
This seems to have been left alone after renaming it in Laravel v9.
See https://github.com/laravel/octane/issues/500
=> [1.x] Update to new forgetScopedInstances method name

src/Commands/StartRoadRunnerCommand.php, src/Commands/StartSwooleCommand.php
Hi,
This is a simple but very helpful change, instead of the bin files used to run the servers being hard coded, they are made configurable.
The reason for doing so is without this developers are forced to extend first the server specific command then the octane:start command if they want to change anything about the boot/worker spawn process.
This is particularly useful for roadrunner if you want to support having roadrunner itself act as a queue consumer as that requires a different setup to PSR7Worker.
The config is defaulted to identical values it had before.
I think the escape hatch it provides is powerful and the increase in maintenance burden is negligible.
=> Make the bin files used by Swoole and Roadrunner config options

bin/createSwooleTimerTable.php, bin/swoole-server, src/Swoole/Actions/EnsureRequestsDontExceedMaxExecutionTime.php, src/Swoole/Handlers/OnServerStart.php
Fix #470
Re-create the new Swoole response object to use it to send the response.
=> Fix max_execution_time config doesn't work

src/Concerns/ProvidesDefaultConfigurationOptions.php, src/Listeners/GiveNewRequestInstanceToPaginator.php
based on our experience PaginationState will use different instance (old instance) of the app and cannot recognize new parameter has been set in the route it seems this was implemented before but commented out.
this PR revert them back but in Listener class it was using `sandbox` not sure what was the reason I change it to `app`
=> Revert PaginationState to resolve using new instance of the app

tests/Listeners/FlushLogContextTest.php
Introduces a test for #513. This is in a separate PR so that #513 can be merged without a failing build and this PR can be merged once the two PRs from `laravel/framework` and `laravel/octane` have both been merged and tagged - otherwise we'll have failing CI.
=> test flushing logger shared context

src/RoadRunner/ServerProcessInspector.php, tests/RoadRunnerServerProcessInspectorTest.php
RoadRunner changed there info output to be send to stderr which leads to an error as Symfony Process threads stderr messages as an error in there callback. With this we remove info output as we should be able to see and error message when it fails in RoadRunner logs and the command it self should fail with and error code.
Here how it would look like when the command could not connect to the RoadRunner server.
```sh
php artisan octane:start --watch  
INFO  Server running…
Local: http://127.0.0.1:8000 
Press Ctrl+C to stop the server
INFO  Application change detected. Restarting workers…
RuntimeException 
Cannot reload RoadRunner: dial tcp 127.0.0.1:10000: connect: connection refused
at vendor/laravel/octane/src/RoadRunner/ServerProcessInspector.php:57
53▕             '-o', …
```
=> add silent option to RoadRunner reset to remove info output which leads to non error

src/Commands/Concerns/InteractsWithIO.php
This pull request avoids the message "worker destroyed" to appear while we reload octane.
=> [1.x] Removes non-needed message

src/Swoole/Handlers/OnWorkerStart.php
Moved opcached clearing to before bootWorker method to enable hot reloading for Swoole and OpenSwoole when Opcache is enabled.
More information about the issue this solves can be seen in #546 .
Closes #546
=> Moved opcache clearing to before bootWorker

src/Listeners/FlushLocaleState.php, tests/LocaleStateTest.php
At the time of this writing, when a "Carbon::setLocale()" call is made within an Octane request, the "locale" state persist to the next request. This pull request fixes that, by reset the Carbon "locale" to the original of the application. 
Fixes #551, and once this pull request is merged and tagged, and we put https://github.com/briannesbitt/Carbon/pull/2640 "Ready to Review".
=> [1.x] Fixes sharing "Carbon" state shared between requests 

composer.json, src/Listeners/FlushLocaleState.php, tests/LocaleStateTest.php, tests/TestCase.php
This pull request fixes the last issue regarding the "locale" update on Vapor apps.
So, the first, got fixed here: https://github.com/laravel/octane/pull/552. And it was regarding the any call to "Carbon::setLocale()" actually changing the local for subsequent requests.
The second, is this one, and concerns the fact that "app->setLocale()" is actually setting the locale of the "app" running the server, and not the app handling the request.
As discussed with Carbon's maintainer, we need the releasing of Carbon, before merging and tagging this pull request: https://github.com/briannesbitt/Carbon/pull/2640.
Fixes https://github.com/laravel/octane/issues/551.
PS: Ignore the tests for now, and I will update this, once the Carbon release is ready.
=> [1.x] Fix carbon locale when setting it via app locale setter

src/Swoole/Handlers/OnServerStart.php, src/Swoole/Handlers/OnWorkerStart.php
This pull request adds support for Swoole 5.
Here is the list of breaking changes, between Swoole 4 and 5: https://github.com/swoole/swoole-src/blob/master/CHANGELOG.md#2022-07-22-v500. Yet, the only change affecting Octane is the removal of `Server::tick`. 
Fixes #559.
=> [1.x] Adds support for Swoole 5

README.md
- https://swoole.co.uk redirects to https://openswoole.com
- https://swoole.com is linked at https://github.com/swoole/swoole-src
=> Update link to OpenSwoole website

.gitignore, src/Commands/StartSwooleCommand.php
In the `StartSwooleCommand`, When [launching the swoole server](https://github.com/laravel/octane/blob/d6c928ba623fa5ea2cf73d43ea02e37a74b7bfff/src/Commands/StartSwooleCommand.php#L80-L86), the command takes only the php executable ignoring any custom options that may be necessary on ones environnement.
Add optional config to specify any custom options to pass to the php executable
```
'swoole' => [
'php_options' => [
'-c',
'/Library/Application Support/appsolute/MAMP PRO/conf/php8.1.1.ini',
],
],
```
=> add possibility to launch swoole server with additional php options

src/Swoole/Actions/EnsureRequestsDontExceedMaxExecutionTime.php
Fix #588
This feature should only be available for Swoole.
OpenSwoole recommends using the [max_request_execution_time](https://openswoole.com/docs/modules/swoole-server/configuration#max_request_execution_time) configuration.
If a new response cannot be created, we can ignore it.
This will fall back to a page hold instead of an exception.
=> [1.x] Ignore `Response::create` failed

bin/roadrunner-worker
This PR implements RoadRunner Relay Overrides (#598), and has no effect unless an environment variable is presented.
In advanced Octane use cases, it may be necessary to override which RoadRunner Relay mechanism is used. This is accomplished by adding the following to your `rr.yaml` file:
```yaml
server:
relay: "unix://rr.sock"
env:
- LARAVEL_OCTANE_ROADRUNNER_RELAY: "unix://rr.sock"
```
As an aside, I'd love to get documentation added for this, but not sure where to go. If you can point me in the right direction, that would be appreciated!
=> RoadRunner Relay Overrides

src/Commands/StartRoadRunnerCommand.php
See https://github.com/laravel/octane/issues/597.
This PR adds a new flag to `octane:roadrunner`; `--log-level`, which defaults to the previous behaviour of basing log level on what environment Laravel is currently running in, but now allows for a manual override.
Example: `php artisan octane:roadrunner --log-level=info`
=> [1.x] Made Roadrunner log level configurable

src/Commands/StartRoadRunnerCommand.php
See https://github.com/laravel/octane/pull/601. This adds a new flag, `--log-level`, to the `octane:roadrunner` command.
Was asked to provide an explanation as to why this broke; it was, simply put, due to an operator precedence issue added in the second commit.
```php
'logs.level='.$this->option('log-level') ?: (app()->environment('local') ? 'debug' : 'warn')
```
Will result in `logs.level=` (no actual level) if no `--log-level` option is given instead of falling back to the old behaviour, due to `.` having higher precedence than `?:`.
Adding parentheses fixes this:
```php
'logs.level='.($this->option('log-level') ?: (app()->environment('local') ? 'debug' : 'warn'))
```
It's perhaps easiest to see with a simpler example:
```php
'foo' . null ?: 'bar'
```
Results in `foo`, while
```php …
```
=> Re-do: Configurable Roadrunner log level

src/Commands/Concerns/InteractsWithServers.php, src/Commands/StartCommand.php, src/Commands/StartRoadRunnerCommand.php, src/Commands/StartSwooleCommand.php
This pull request aims to add support for defining the HTTP server port through environment variables. The implementation shouldn't break any existing behavior.
This feature should be helpful for anyone that needs to run octane with a randomly generated port.
=> [1.x] Read port for http server from environment if no port is passed 

composer.json, tests/RequestStateTest.php
This pull request adds tests for https://github.com/laravel/octane/issues/594, and it it's waiting for a framework release before being "ready for review".
=> [1.x] Adds tests regarding flushing controller is computed middleware

src/Commands/Concerns/InteractsWithServers.php, src/Commands/StartCommand.php, src/Commands/StartRoadRunnerCommand.php, src/Commands/StartSwooleCommand.php
Building further on #605 this also makes the IP that the server listens on configurable using environment variables when no commandline argument for `--host` is provided.
The implementation should not break any existing deployments.
=> [1.x] Make IP to bind the server to configurable via env

src/Commands/Concerns/InstallsRoadRunnerDependencies.php
This resolves the issue described [here](https://github.com/laravel/octane/issues/610).
On php 8.1 octane errors out because it's unable to start the rr binary that gets downloaded. It's unable to because it doesn't have permission, because the `chmod()` that gets run after the binary is installed, doesn't have the right value for permissions. It's trying to set them to `755` but per the [chmod documentation](https://www.php.net/manual/en/function.chmod.php), you need to use a `0` prefix to specify it as an octal value. 
This PR adds the `0` prefix to the permissions, setting them to `0755` which runs successfully on php 8.1.
=> Prefix rr binary permissions with 0 to specify it as an octal value

tests/RoadRunnerClientTest.php, tests/SwooleClientTest.php
This pull request fixes the test suite due a change in the `testbench` package.
=> [1.x] Fixes `test_error_method_sends_error_response_to_roadrunner` test

src/Commands/Concerns/InteractsWithIO.php
We noticed that on PHP 8.1, we are receiving the following deprecation notice in Sentry.
```txt
json_encode(): Passing null to parameter #2 ($flags) of type int is deprecated in /var/www/vendor/laravel/octane/src/Commands/Concerns/InteractsWithIO.php on line 237
```
It looks like this is just a typo, and the verbosity should be passed to `info()` not to `json_encode()`. 👍🏻
=> fix: resolve typo resulting in deprecation notice

.github/workflows/tests.yml
Unrelated to the test failures, this just cleans up all the deprecated Node.js v12 notices.
=> ci: update `actions/checkout` to v3

composer.json
This should fix the issues with the Testbench `vendor` directory not existing. When any `testbench` command is run, it creates the symlink if it does not exist.
=> fix: ensure Testbench `vendor` symlink exists

src/Commands/StartCommand.php, src/Commands/StartRoadRunnerCommand.php
This PR adds the `--rpc-host` option to be used for the Roadrunner server. Its value defaults to the `--host` option to preserve backward compatibility.
When deploying to AWS ECS as a Docker container and Nginx sidecar, the `--host` option must be set to `0.0.0.0` to listen to any host.
However, the RPC host needs to be set to the loopback interface `127.0.0.1`. The current logic sets both hosts to the same, making this impossible to configure.
We've already implemented this as a custom command on our own codebase, which has been deployed to a production environment and is successfully working as we expect.
---
Without this, we get a bunch of `network error` logs and the task is never able to start due to the server being unable to respond to any requests:
=> Add `--rpc-host` option for Roadrunner

.github/workflows/tests.yml
The project `composer.json` already contain `laravel/framework` under `require` and having this line replace the "locked" supported versions.
These changes would also allow us to add `--prefer-lowest` build.
=> Require "laravel/framework" using `--dev` for build

src/Commands/Concerns/InteractsWithIO.php
This pull request makes Octane ignore some internal messages on the Octane output:
=> [1.x] Removes internal messages from output

src/Commands/Concerns/InteractsWithIO.php
This pull request addresses https://github.com/laravel/octane/issues/637, by only displaying the source file and line, when those all available.
=> [1.x] Only displays source when there is source

src/Swoole/SwooleClient.php, tests/SwooleClientTest.php
Closes #641 
Following the Symfony's implementation, any empty string or `null` value will instead use string `deleted`. To avoid issues with strings like `0` (which are valid cookie values) I'm not using the `?:` op.
=> Fix unsetting a cookie value when using Swoole

bin/swoole-server
Fixes #632 by not bootstrapping on `managerstart`. Previously, the Composer autoload files were being included before server / worker start and thus could not be gracefully reloaded to update the class map / PSR-4 mappings.
=> Allow graceful reload after installing packages

config/octane.php, src/Swoole/SwooleClient.php, tests/SwooleClientTest.php
This PR will enable users to add custom HTTP headers on files served from the public directory. This is important for production applications that could benefit from configuring a `Cache-Control` policy for their web assets. I have included an example policy to show how the new configuration option can be used.
This change should be backwards compatible as it checks if the new configuration option is present in `config/octane.php`.
=> Add support for custom HTTP headers on static files

src/Commands/StartRoadRunnerCommand.php, src/Swoole/SwooleClient.php
The return value of rpcHost should be string.
`empty()` is essentially the concise equivalent to `!isset($var) || $var == false`, so it doesn't need to be processed`?? []`
=> Fix return value error and Remove useless code

src/Concerns/ProvidesRouting.php
This PR is a required dep to this pr in the main repo.
this method is required to get octane specific routes for caching. 
https://github.com/laravel/framework/pull/46448
=> [1.x] Add method to fix octane route caching. 

bin/createSwooleServer.php
Support users to set their own Swoole Server mode.
After Swoole 5, the default mode is `SWOOLE_BASE` mode.
=> Support setting swoole server mode

src/Concerns/ProvidesDefaultConfigurationOptions.php, src/Listeners/GiveNewApplicationInstanceToCacheManager.php
Related PR: laravel/framework#46594
=> [1.x] Give new app instance to cache manager

src/Concerns/ProvidesDefaultConfigurationOptions.php, src/Listeners/GiveNewApplicationInstanceToSessionManager.php
Related PR: laravel/framework#46621
=> [1.x] Give new container instance to session manager

src/Listeners/GiveNewApplicationInstanceToSessionManager.php
This pull request reverts #669, fixing https://github.com/laravel/octane/issues/674, and https://github.com/laravel/octane/issues/673, and the reports of users not being able to see run Octane and see logs.
=> [1.x] Reverts #669

src/Commands/Concerns/InteractsWithServers.php, src/Contracts/ServerProcessInspector.php, src/RoadRunner/ServerProcessInspector.php, src/Swoole/ServerProcessInspector.php
=> add ServerProcessInspector interface

composer.json, src/Commands/Concerns/InstallsRoadRunnerDependencies.php, src/Commands/StartRoadRunnerCommand.php
This PR adds support for `spiral/roadrunner-http` v3
The [`spiral/roadrunner`](https://packagist.org/packages/spiral/roadrunner) now is a meta package and does not require `spiral/roadrunner-http` anymore, so I've changed the requirements to `spiral/roadrunner-http` (and `spiral/roadrunner-cli` which is required to download the roadrunner binary) instead of `spiral/roadrunner`.
The other required change is the configuration `version`, that must be set to `3` for the new version,  and is set dynamically based on roadrunner binary version
=> Support roadrunner http v3

tests/SwooleClientTest.php
No idea why these tests have been skipped on openswoole - but these are running for me locally ... let's see what ci says ....
=> test: run SwooleClientTest on openswoole as well.

src/Swoole/SwooleClient.php, tests/SwooleClientTest.php
With this Pull Request i want to fix a bug where Swoole is formatting headers names unintentionally.
Swoole and Open Swoole are formatting headers by default.
https://openswoole.com/docs/modules/swoole-http-response-header
It seems odd that octane calles ResponseHeaderBag's allPreserveCase presumably to preserve the casing.
https://github.com/laravel/octane/blob/d962806a79c5ac97ddd1e371bd232d00c855c0d9/src/Swoole/SwooleClient.php#L156
But few lines later swoole will format it.
https://github.com/laravel/octane/blob/d962806a79c5ac97ddd1e371bd232d00c855c0d9/src/Swoole/SwooleClient.php#L164
The swoole formatting should be adjustable by config, so it could be behave like Laravel and Symfony by default.
This change is backwards compatible, because the default is still "true".
on-behalf-of: …
=> [Bug][Swoole] Disable unintentional swoole header formatting by config value

bin/roadrunner-worker
As of the time of writing, we have documented that customers should stop their Octane servers using the "octane:stop" command. However, it appears that some customers are sending a SIGTERM signal to the "octane:start" command, as reported in this GitHub issue: https://github.com/laravel/octane/issues/713. Specifically, during local development, people often use the `Control + C` shortcut in their terminals.
Although behind the scenes, we do invoke the "octane:stop" command when a `SIGTERM` signal is sent to the `StartRoadRunnerCommand`, there is an issue with the fact that "octane:stop" does not wait for the underlying worker to stop completely. As a result, there is a possibility that the worker may attempt to communicate with the master process (like a regular Laravel response with …
=> [2.x] Fixes "Incorrect header size"

src/Commands/Concerns/InstallsRoadRunnerDependencies.php
This pull request fixes the installation of Octane (RoadRunner) when using something like Herd.
Before:
```
Octane requires "spiral/roadrunner-http:^3.0.1" and "spiral/roadrunner-cli:^2.5.0". Do you wish to install them as a dependencies? (yes/no) [no]:
> yes
Could not open input file: /Users/nunomaduro/Library/Application
```
After:
```
Octane requires "spiral/roadrunner-http:^3.0.1" and "spiral/roadrunner-cli:^2.5.0". Do you wish to install them as a dependencies? (yes/no) [no]:
> yes
./composer.json has been updated
Running composer update spiral/roadrunner-http spiral/roadrunner-cli --with-all-dependencies
Loading composer repositories with package information
...
```
=> [2.x] Fixes installation when using Herd

bin/createSwooleServer.php
Currently creating a swoole server will result in it always listening on an IPv4 socket regardless of the host address configured.
This change will use the listen host address to determine whether Swoole should listen on an IPv4 or IPv6 socket.
Previously a swoole server configured to listen on `::` would show up in `netstat` as listening on a `0.0.0.0` address, 
whereas now it will correctly show it as listening on the `::` address.
=> Add IPv6 support for Swoole

src/Swoole/Actions/EnsureRequestsDontExceedMaxExecutionTime.php
Fixes laravel/octane#545 and potential fix for laravel/octane#712
=> Fix passing invalid connection session id to `Swoole\Http\Response::create()`

bin/createSwooleServer.php
Support for setting mode in config file. `mode` add via #666
close #739
=> Fix missing mode config

src/Commands/Concerns/InteractsWithIO.php
To implement the filebeat logs in stdout during the execution of the project with octane, all outputs are displayed with the info method in the output, which causes a change in the output of stdout and makes it difficult to implement filebeat using stdout.
My suggestion is to create a new type in the handleStream method and use it whenever we need to send a specific json in the output.
=> Add “raw” type in handleStream method for custom json in stdout

src/Commands/Concerns/InstallsRoadRunnerDependencies.php, src/Commands/Concerns/InteractsWithIO.php, src/Commands/StartRoadRunnerCommand.php
This pull request adds Herd support to Octane, note that it can't be released yet because we need to wait for RoadRunner `2023.3.0`.
=> [2.x] Adds Herd support

bin/createSwooleServer.php, src/Commands/StartCommand.php, src/Commands/StartRoadRunnerCommand.php, src/Commands/StartSwooleCommand.php
When attempting to configure Swoole to bind on a different host using anything except `--host` in the commandline, it wouldn't work and always stick to `127.0.0.1`.
Additionally, `bin/createSwooleServer.php` contains a default port value of `8080` despite the [command stating](https://github.com/laravel/octane/blob/d6b29ee456d00ebf359685ff952b6b55a1230592/src/Commands/StartCommand.php#L19) the default is `8000`.
- When you configure the config value `octane.host`, the `$serverState['host']` will stay at `127.0.0.1`, and only `$serverState['octaneConfig']['host']` changes to the configured value. 
- `src/Commands/StartCommand.php` is using a default value of `127.0.0.1` for `--host` when this argument is not provided in the command. But because …
=> Fix swoole host only configurable via --host parameter + incorrect default port

src/Swoole/SwooleClient.php
fix #767
Support http code 425 by setting reason
https://github.com/laravel/octane/blob/1685e81548e2ee640d558d4281a1269594d5fee0/src/Swoole/SwooleClient.php#L172-L176
=> Fix missing http code 425 reason.

src/Commands/Concerns/InteractsWithIO.php
This pull request ignores `write error` message for now, while @dunglas updates the message to `DEBUG` level. 
https://github.com/dunglas/frankenphp/blob/b7c8d4cd490ba4a869b3021a10a1ca5423e9e2cc/frankenphp.go#L519
=> [2.x] Ignores `write error` message for now

src/Commands/StartFrankenPhpCommand.php, src/Commands/stubs/Caddyfile, src/FrankenPhp/ServerProcessInspector.php
This pull request adds support for multiple FrankenPHP Octane instances.
=> [2.x] Adds support for multiple FrankenPHP Octane instances

src/Commands/Concerns/InstallsFrankenPhpDependencies.php
This pull request improves the version fetching, as apparently the builds in different OSs display the version differently. So, using a `build-info` command is a better, more reliable way.
Fixes https://github.com/laravel/octane/issues/774, https://github.com/laravel/octane/issues/771.
=> [2.x] Improves version fetching

bin/frankenphp-worker.php, src/Commands/StartFrankenPhpCommand.php
Allows to set Octane's max execution time using the configuration file just like in RoadRunner or Swoole.
=> [2.x] Uses Octane's max execution time

src/Commands/StartCommand.php, src/Commands/StartFrankenPhpCommand.php
This pull request adds the  `--admin-port` option, in case Octane is not able to determine the admin port by himself.
=> [2.x] Adds `--admin-port`

src/Commands/StartRoadRunnerCommand.php
This pull request fix problem with roadrunner static dir when it`s not default `public` directory in root of project.
For example in one of my project it need to be set to `site/public`.
=> Fix public path for roadrunner

composer.json
As mentioned in [https://github.com/laravel/octane/issues/796](https://github.com/laravel/octane/issues/796)
This PR makes octane require pcntl extension.
=> [2.x] Require pcntl extension
